// <auto-generated />
namespace ProductStockTracking.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class configure10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(configure10));
        
        string IMigrationMetadata.Id
        {
            get { return "202005011933349_configure10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
