// <auto-generated />
namespace ProductStockTracking.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class configure7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(configure7));
        
        string IMigrationMetadata.Id
        {
            get { return "202004272311145_configure7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
